---
kind: Pod 
apiVersion: v1 
metadata:
  name: myweb 
  namespace: prodns 
spec: 
   containers:
    - name: nginx-container
      image: nginx:1.14
      env:
        - name: DB_ID
          value: developer
        - name: DB_PASS
          value: developer
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 1
          memory: 1Gi

