--- 
kind: Pod 
apiVersion: v1 
metadata: 
  name: web-pvc 
spec: 
  containers:
    - name: nginx
      image: nginx:1.14 
      ports: 
        - containerPort: 80
          name: web-port
      #2) 볼륨 마운트
      # mount [pvc] /usr/share/nginx/html
      volumeMounts: 
        - name: html 
          mountPath: /usr/share/nginx/html
  # 1) 볼륨 정의
  volumes: 
    - name: html 
      persistentVolumeClaim: 
        claimName: pvc-web 