--- 
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: pvc-web 
spec: 
  # 볼륨 특성으로 선택 
  resources:
    requests:
      storage: 4Gi 
  accessModes: 
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: manual 
  volumeMode: Filesystem 