---
kind: ReplicaSet 
apiVersion: apps/v1 
metadata: 
  name: mainui-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      name: apache
      app: main 
      rel: stable 
  template:
    metadata: 
      name: httpd-container 
      labels: 
        name: apache
        app: main 
        rel: stable 
    spec: 
      containers:
        - name: httpd-container 
          image: httpd:2.2 
          ports: 
            - containerPort: 80
