--- 
kind: Pod 
apiVersion: v1 
metadata: 
  name: mongodb-pod 
spec: 
  containers: 
    - name: mongodb-container 
      image: mongo 
      ports: 
        - containerPort: 27017 
  affinity: 
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels: 
              app: tensor 
          topologyKey: kubernetes.io/hostname