--- 
kind: Pod 
apiVersion: v1 
metadata: 
  name: tensorflow-pod
  labels: 
    app: tensor 
spec:
  containers: 
    - name: tensorfolow
      image: tensorflow/tensorflow:nightly-jupyter
  nodeSelector: 
    disktype: ssd
    gpu: "true"
  
    