apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: f964757154be1bd935342c93b4dedb0c05c9a300caab0edcd9a968eb0f9caa26
    cni.projectcalico.org/podIP: 172.16.104.19/32
    cni.projectcalico.org/podIPs: 172.16.104.19/32
  creationTimestamp: "2025-10-15T08:59:39Z"
  generation: 1
  labels:
    run: testpod
  name: testpod
  namespace: default
  resourceVersion: "380903"
  uid: 14ad9f48-0a41-4499-b2d8-66e8161839ca
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: testpod
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-72cmp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: regcred
  nodeName: node2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccountName: pod-viewer
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-72cmp
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-10-15T08:59:42Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-10-15T08:59:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-10-15T08:59:42Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-10-15T08:59:42Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-10-15T08:59:39Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://c5e6efbdd39aa3983acd0ddb417895b50bf49659bbd929ebe7fc2c817bfe0d6b
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:3b7732505933ca591ce4a6d860cb713ad96a3176b82f7979a8dfa9973486a0d6
    lastState: {}
    name: testpod
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-10-15T08:59:42Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-72cmp
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.10.12
  hostIPs:
  - ip: 192.168.10.12
  phase: Running
  podIP: 172.16.104.19
  podIPs:
  - ip: 172.16.104.19
  qosClass: BestEffort
  startTime: "2025-10-15T08:59:39Z"
